### ISSUE TITLE
ENOENT on ** globs

### ISSUE THREAD

**Issue by vpArth** [peter-vilja/gulp-clean#17]
Hi guys.

Here is simple clean task:  

```js
gulp.task('clean', function () {
  return gulp.src('js/**', {read: false})
    .pipe(clean({force: true}));
});
```

My issue is hierarchy, for example

```
js/
js/modules/1.js
```  

in this case, `modules` removes first, and when `clean` try to remove `1.js`, `ENOENT` throwed.  

Is there a way to handle `**` globs in correct order(files, then dirs)? 
 Or is there other glob to remove all in folder?

Thanks.

**Comment by bonfish** [comment]
@vpArth, I had the same problem solved by specifying an array of globs: first setting the one for files and then the universal one. Like this:
```
gulp.src(['js/**/*.js', 'js/**'], {read: false});
```
That way, the files seem to be selected prior to folders. 

It looks like an issue of gulp itself or even `glob-stream`, not the plugin.

**Comment by vpArth** [comment]
Thanks, @bonfish. I solve it almost same way :)
But I think it's not so hard to add some `silent` flag, which will just ignore absent files, while clean.

**Comment by xlaywan** [comment]
+1 for the https://github.com/peter-vilja/gulp-clean/issues/17#issuecomment-84815442

**Comment by rbarilani** [comment]
The solution of @xlaywan doesn't work in my case.

**Comment by vpArth** [comment]
Repo is deprecated
