### ISSUE TITLE
what's the different between gulp-clean and del?

### ISSUE THREAD

**Issue by flynntsc** [peter-vilja/gulp-clean#22]
del is [here](https://www.npmjs.com/package/del)

**Comment by peter-vilja** [comment]
gulp-clean is a gulp plugin whereas del is just a node module. del can be used almost anywhere whereas gulp-clean is more tightly coupled with gulp. Gulp supports async tasks when the task returns a Promise. del returns a Promise which makes it easy to use with gulp. Recommended way to delete files and folders can be found here https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md. (currently it's with del module)

**Comment by flynntsc** [comment]
thanks a lot
